/**
 * Kept.ai — Company Datasets
 * Fake datasets for demo dashboard switching
 */

const COMPANIES = {
  'acme-apparel': {
    name: 'Acme Apparel Co.',
    initials: 'AC',
    industry: 'Fashion & Apparel',
    avgReturnCost: 55.2,
    avgOrderValue: 96.3,
    datasets: {
      '7D': [
        { label: 'Jan 25', orders: 107, returns: 19, prevented: 13, returnRate: 17.8 },
        { label: 'Jan 26', orders: 96,  returns: 15, prevented: 9,  returnRate: 15.6 },
        { label: 'Jan 27', orders: 119, returns: 21, prevented: 14, returnRate: 17.6 },
        { label: 'Jan 28', orders: 137, returns: 25, prevented: 17, returnRate: 18.2 },
        { label: 'Jan 29', orders: 114, returns: 19, prevented: 12, returnRate: 16.7 },
        { label: 'Jan 30', orders: 143, returns: 26, prevented: 19, returnRate: 18.2 },
        { label: 'Jan 31', orders: 126, returns: 20, prevented: 14, returnRate: 15.9 },
      ],
      '30D': [
        { label: 'Jan 1',  orders: 147, returns: 32, prevented: 13, returnRate: 21.8 },
        { label: 'Jan 3',  orders: 129, returns: 26, prevented: 12, returnRate: 20.2 },
        { label: 'Jan 5',  orders: 131, returns: 27, prevented: 15, returnRate: 20.6 },
        { label: 'Jan 7',  orders: 117, returns: 23, prevented: 11, returnRate: 19.7 },
        { label: 'Jan 9',  orders: 136, returns: 27, prevented: 16, returnRate: 19.9 },
        { label: 'Jan 11', orders: 123, returns: 23, prevented: 13, returnRate: 18.7 },
        { label: 'Jan 13', orders: 121, returns: 23, prevented: 14, returnRate: 19.0 },
        { label: 'Jan 15', orders: 129, returns: 23, prevented: 14, returnRate: 17.8 },
        { label: 'Jan 17', orders: 124, returns: 23, prevented: 15, returnRate: 18.5 },
        { label: 'Jan 19', orders: 113, returns: 19, prevented: 12, returnRate: 16.8 },
        { label: 'Jan 21', orders: 129, returns: 23, prevented: 15, returnRate: 17.8 },
        { label: 'Jan 23', orders: 118, returns: 19, prevented: 12, returnRate: 16.1 },
        { label: 'Jan 25', orders: 107, returns: 19, prevented: 13, returnRate: 17.8 },
        { label: 'Jan 27', orders: 119, returns: 21, prevented: 14, returnRate: 17.6 },
        { label: 'Jan 31', orders: 126, returns: 20, prevented: 14, returnRate: 15.9 },
      ],
      '3M': [
        { label: 'Nov W1', orders: 883, returns: 214, prevented: 39, returnRate: 24.2 },
        { label: 'Nov W2', orders: 967, returns: 234, prevented: 51, returnRate: 24.2 },
        { label: 'Nov W3', orders: 1013, returns: 237, prevented: 48, returnRate: 23.4 },
        { label: 'Nov W4', orders: 974, returns: 238, prevented: 47, returnRate: 24.4 },
        { label: 'Dec W1', orders: 1043, returns: 231, prevented: 65, returnRate: 22.1 },
        { label: 'Dec W2', orders: 1087, returns: 237, prevented: 76, returnRate: 21.8 },
        { label: 'Dec W3', orders: 1034, returns: 221, prevented: 73, returnRate: 21.4 },
        { label: 'Dec W4', orders: 957, returns: 219, prevented: 77, returnRate: 22.9 },
        { label: 'Jan W1', orders: 913, returns: 178, prevented: 79, returnRate: 19.5 },
        { label: 'Jan W2', orders: 887, returns: 173, prevented: 83, returnRate: 19.5 },
        { label: 'Jan W3', orders: 843, returns: 155, prevented: 76, returnRate: 18.4 },
        { label: 'Jan W4', orders: 809, returns: 149, prevented: 81, returnRate: 18.4 },
      ],
      '1Y': [
        { label: 'Feb',  orders: 1973, returns: 489, prevented: 0,   returnRate: 24.8 },
        { label: 'Mar',  orders: 2063, returns: 541, prevented: 0,   returnRate: 26.2 },
        { label: 'Apr',  orders: 2114, returns: 547, prevented: 0,   returnRate: 25.9 },
        { label: 'May',  orders: 2071, returns: 563, prevented: 0,   returnRate: 27.2 },
        { label: 'Jun',  orders: 2193, returns: 596, prevented: 0,   returnRate: 27.2 },
        { label: 'Jul',  orders: 2327, returns: 647, prevented: 0,   returnRate: 27.8 },
        { label: 'Aug',  orders: 2874, returns: 827, prevented: 0,   returnRate: 28.8 },
        { label: 'Sep',  orders: 3023, returns: 851, prevented: 38,  returnRate: 28.2, tag: 'Kept starts' },
        { label: 'Oct',  orders: 3271, returns: 879, prevented: 113, returnRate: 26.9 },
        { label: 'Nov',  orders: 3857, returns: 931, prevented: 191, returnRate: 24.1 },
        { label: 'Dec',  orders: 4093, returns: 893, prevented: 287, returnRate: 21.8 },
        { label: 'Jan',  orders: 3462, returns: 662, prevented: 323, returnRate: 19.1 },
      ],
      'ALL': [
        { label: 'Q1 24', orders: 4183,  returns: 871,  prevented: 0,   returnRate: 20.8 },
        { label: 'Q2 24', orders: 5127,  returns: 1139, prevented: 0,   returnRate: 22.2 },
        { label: 'Q3 24', orders: 5784,  returns: 1318, prevented: 0,   returnRate: 22.8 },
        { label: 'Q4 24', orders: 6213,  returns: 1503, prevented: 0,   returnRate: 24.2 },
        { label: 'Q1 25', orders: 5876,  returns: 1457, prevented: 0,   returnRate: 24.8 },
        { label: 'Q2 25', orders: 6381,  returns: 1672, prevented: 0,   returnRate: 26.2 },
        { label: 'Q3 25', orders: 7397,  returns: 2063, prevented: 38,  returnRate: 27.9, tag: 'Kept starts' },
        { label: 'Q4 25', orders: 11221, returns: 2703, prevented: 591, returnRate: 24.1 },
        { label: 'Jan 26', orders: 3462, returns: 662,  prevented: 323, returnRate: 19.1 },
      ],
    },
    reasonsData: [
      { name: 'Size / Fit Issues', pct: 41, count: 269, color: '#073159' },
      { name: 'Not as Described',  pct: 19, count: 125, color: '#2E9CDB' },
      { name: 'Quality Issues',    pct: 16, count: 105, color: '#3B4A6B' },
      { name: 'Changed Mind',      pct: 11, count: 72,  color: '#5BB8E8' },
      { name: 'Arrived Damaged',   pct: 7,  count: 46,  color: '#A0AEC0' },
      { name: 'Other',             pct: 6,  count: 39,  color: '#CBD5E0' },
    ],
    products: [
      {
        id: 'olb-2024', name: 'Oversized Linen Blazer', cat: 'Outerwear',
        sku: 'OLB-2024', price: 128, sold: 423, returned: 151, returnRate: 35.7,
        topReason: 'Wrong Size', reasonPct: 81, returnCost: 8247, risk: 'critical',
      },
      {
        id: 'hwj-1189', name: 'High-Rise Wide Leg Jean', cat: 'Bottoms',
        sku: 'HWJ-1189', price: 89, sold: 694, returned: 231, returnRate: 33.3,
        topReason: 'Wrong Size', reasonPct: 74, returnCost: 11342, risk: 'critical',
      },
      {
        id: 'mod-3302', name: 'Mesh Overlay Midi Dress', cat: 'Dresses',
        sku: 'MOD-3302', price: 156, sold: 329, returned: 103, returnRate: 31.3,
        topReason: "Didn't Match Photos", reasonPct: 68, returnCost: 7213, risk: 'high',
      },
      {
        id: 'cps-0891', name: 'Chunky Platform Sneaker', cat: 'Footwear',
        sku: 'CPS-0891', price: 112, sold: 517, returned: 153, returnRate: 29.6,
        topReason: 'Wrong Size', reasonPct: 72, returnCost: 8419, risk: 'high',
      },
    ],
    aiInsights: {
      'olb-2024': {
        product: 'Oversized Linen Blazer — OLB-2024',
        summary: '81% of returns cite "Wrong Size." Customer review analysis reveals the blazer runs 1.5 sizes larger than standard. The size chart references body measurements but doesn\'t account for the intentional oversized fit.',
        actions: [
          { priority: 'high', text: 'Update size chart to include "Oversized Fit" guidance — recommend sizing down 1–2 sizes.', impact: 'Est. -18% return rate → saves ~$2,900/quarter' },
          { priority: 'high', text: 'Add a checkout fit warning triggered when cart size matches customer\'s usual size.', impact: 'Est. -12% return rate → saves ~$1,950/quarter' },
          { priority: 'medium', text: 'Reshoot product images to show the blazer on models of varying body types with size labels visible.', impact: 'Est. -6% return rate → saves ~$975/quarter' },
        ]
      },
      'hwj-1189': {
        product: 'High-Rise Wide Leg Jean — HWJ-1189',
        summary: '74% of returns cite "Wrong Size." Inseam length is the primary complaint — the product page lists a single inseam (32") but doesn\'t offer length options.',
        actions: [
          { priority: 'high', text: 'Introduce short (28"), regular (30"), and long (32") inseam options.', impact: 'Est. -22% return rate → saves ~$4,850/quarter' },
          { priority: 'high', text: 'Deploy the Kept checkout widget with height-based inseam recommendations.', impact: 'Est. -10% return rate → saves ~$2,200/quarter' },
          { priority: 'medium', text: 'Add waist-to-hip ratio guidance in the size chart.', impact: 'Est. -5% return rate → saves ~$1,100/quarter' },
        ]
      },
      'mod-3302': {
        product: 'Mesh Overlay Midi Dress — MOD-3302',
        summary: '68% of returns cite "Didn\'t Match Photos." The studio lighting makes the mesh overlay appear sheer, but in person the fabric is more opaque.',
        actions: [
          { priority: 'high', text: 'Reshoot product photos in natural lighting and include close-up texture shots.', impact: 'Est. -15% return rate → saves ~$2,240/quarter' },
          { priority: 'medium', text: 'Add a 15-second video showing the dress in motion and in different lighting.', impact: 'Est. -10% return rate → saves ~$1,490/quarter' },
          { priority: 'low', text: 'Update description to "structured overlay" rather than "delicate mesh."', impact: 'Est. -4% return rate → saves ~$600/quarter' },
        ]
      },
      'cps-0891': {
        product: 'Chunky Platform Sneaker — CPS-0891',
        summary: '72% of returns cite "Wrong Size." The platform sole adds 2 inches affecting internal fit — the toe box runs narrow at the platform junction.',
        actions: [
          { priority: 'high', text: 'Add "Runs narrow — recommend ordering a half size up" as a prominent callout.', impact: 'Est. -16% return rate → saves ~$2,760/quarter' },
          { priority: 'high', text: 'Fix EU/UK size conversion table — off by 0.5 sizes for EU 38–42.', impact: 'Est. -8% return rate → saves ~$1,380/quarter' },
          { priority: 'medium', text: 'Add foot width guidance (narrow/regular/wide) and recommend sizing up for wide feet.', impact: 'Est. -5% return rate → saves ~$865/quarter' },
        ]
      },
    },
    returnRateTrend: [
      { label: 'Aug', rate: 28.8 },
      { label: 'Sep', rate: 28.2 },
      { label: 'Oct', rate: 26.9 },
      { label: 'Nov', rate: 24.1 },
      { label: 'Dec', rate: 21.8 },
      { label: 'Jan', rate: 19.1 },
    ],
    channelData: [
      { channel: 'Online Store', returns: 3214, pct: 58, rate: 24.3 },
      { channel: 'Marketplace', returns: 1321, pct: 24, rate: 19.7 },
      { channel: 'Mobile App', returns: 689, pct: 13, rate: 15.2 },
      { channel: 'In-Store', returns: 278, pct: 5, rate: 8.1 },
    ],
    interventions: [
      { type: 'Size Guide Prompt', triggered: 412, prevented: 147, rate: 35.7 },
      { type: 'Fit Confirmation', triggered: 234, prevented: 89, rate: 38.0 },
      { type: 'True Color Modal', triggered: 156, prevented: 52, rate: 33.3 },
      { type: 'Review Highlights', triggered: 89, prevented: 24, rate: 27.0 },
    ],
  },

  'luxe-beauty': {
    name: 'Luxe Beauty Co.',
    initials: 'LB',
    industry: 'Beauty & Cosmetics',
    avgReturnCost: 23.7,
    avgOrderValue: 52.5,
    datasets: {
      '7D': [
        { label: 'Jan 25', orders: 213, returns: 24, prevented: 9,  returnRate: 11.3 },
        { label: 'Jan 26', orders: 192, returns: 19, prevented: 6,  returnRate: 9.9 },
        { label: 'Jan 27', orders: 227, returns: 26, prevented: 11, returnRate: 11.5 },
        { label: 'Jan 28', orders: 248, returns: 26, prevented: 12, returnRate: 10.5 },
        { label: 'Jan 29', orders: 217, returns: 21, prevented: 8,  returnRate: 9.7 },
        { label: 'Jan 30', orders: 253, returns: 29, prevented: 13, returnRate: 11.5 },
        { label: 'Jan 31', orders: 237, returns: 23, prevented: 9,  returnRate: 9.7 },
      ],
      '30D': [
        { label: 'Jan 1',  orders: 263, returns: 37, prevented: 9,  returnRate: 14.1 },
        { label: 'Jan 3',  orders: 242, returns: 32, prevented: 8,  returnRate: 13.2 },
        { label: 'Jan 5',  orders: 241, returns: 32, prevented: 10, returnRate: 13.3 },
        { label: 'Jan 7',  orders: 223, returns: 27, prevented: 7,  returnRate: 12.1 },
        { label: 'Jan 9',  orders: 247, returns: 29, prevented: 11, returnRate: 11.7 },
        { label: 'Jan 11', orders: 237, returns: 28, prevented: 11, returnRate: 11.8 },
        { label: 'Jan 13', orders: 219, returns: 24, prevented: 8,  returnRate: 11.0 },
        { label: 'Jan 15', orders: 243, returns: 27, prevented: 11, returnRate: 11.1 },
        { label: 'Jan 17', orders: 226, returns: 23, prevented: 8,  returnRate: 10.2 },
        { label: 'Jan 19', orders: 218, returns: 23, prevented: 10, returnRate: 10.6 },
        { label: 'Jan 21', orders: 232, returns: 23, prevented: 9,  returnRate: 9.9 },
        { label: 'Jan 23', orders: 228, returns: 24, prevented: 10, returnRate: 10.5 },
        { label: 'Jan 25', orders: 213, returns: 24, prevented: 9,  returnRate: 11.3 },
        { label: 'Jan 27', orders: 227, returns: 26, prevented: 11, returnRate: 11.5 },
        { label: 'Jan 31', orders: 237, returns: 23, prevented: 9,  returnRate: 9.7 },
      ],
      '3M': [
        { label: 'Nov W1', orders: 1587, returns: 251, prevented: 19, returnRate: 15.8 },
        { label: 'Nov W2', orders: 1734, returns: 262, prevented: 31, returnRate: 15.1 },
        { label: 'Nov W3', orders: 1793, returns: 258, prevented: 29, returnRate: 14.4 },
        { label: 'Nov W4', orders: 1712, returns: 253, prevented: 33, returnRate: 14.8 },
        { label: 'Dec W1', orders: 1887, returns: 261, prevented: 39, returnRate: 13.8 },
        { label: 'Dec W2', orders: 1963, returns: 259, prevented: 51, returnRate: 13.2 },
        { label: 'Dec W3', orders: 1871, returns: 241, prevented: 47, returnRate: 12.9 },
        { label: 'Dec W4', orders: 1743, returns: 231, prevented: 49, returnRate: 13.3 },
        { label: 'Jan W1', orders: 1691, returns: 207, prevented: 53, returnRate: 12.2 },
        { label: 'Jan W2', orders: 1614, returns: 183, prevented: 47, returnRate: 11.3 },
        { label: 'Jan W3', orders: 1567, returns: 176, prevented: 51, returnRate: 11.2 },
        { label: 'Jan W4', orders: 1493, returns: 154, prevented: 46, returnRate: 10.3 },
      ],
      '1Y': [
        { label: 'Feb',  orders: 3617, returns: 621, prevented: 0,   returnRate: 17.2 },
        { label: 'Mar',  orders: 3783, returns: 674, prevented: 0,   returnRate: 17.8 },
        { label: 'Apr',  orders: 3961, returns: 721, prevented: 0,   returnRate: 18.2 },
        { label: 'May',  orders: 4087, returns: 772, prevented: 0,   returnRate: 18.9 },
        { label: 'Jun',  orders: 4317, returns: 825, prevented: 0,   returnRate: 19.1 },
        { label: 'Jul',  orders: 4481, returns: 887, prevented: 0,   returnRate: 19.8 },
        { label: 'Aug',  orders: 5213, returns: 1103, prevented: 0,  returnRate: 21.2 },
        { label: 'Sep',  orders: 5487, returns: 1092, prevented: 31, returnRate: 19.9, tag: 'Kept starts' },
        { label: 'Oct',  orders: 5821, returns: 1058, prevented: 69, returnRate: 18.2 },
        { label: 'Nov',  orders: 6783, returns: 1073, prevented: 127, returnRate: 15.8 },
        { label: 'Dec',  orders: 7214, returns: 1019, prevented: 197, returnRate: 14.1 },
        { label: 'Jan',  orders: 6087, returns: 664, prevented: 207, returnRate: 10.9 },
      ],
      'ALL': [
        { label: 'Q1 24', orders: 8423,  returns: 1193, prevented: 0,   returnRate: 14.2 },
        { label: 'Q2 24', orders: 9781,  returns: 1457, prevented: 0,   returnRate: 14.9 },
        { label: 'Q3 24', orders: 11237, returns: 1810, prevented: 0,   returnRate: 16.1 },
        { label: 'Q4 24', orders: 11983, returns: 2037, prevented: 0,   returnRate: 17.0 },
        { label: 'Q1 25', orders: 11417, returns: 2069, prevented: 0,   returnRate: 18.1 },
        { label: 'Q2 25', orders: 12387, returns: 2338, prevented: 0,   returnRate: 18.9 },
        { label: 'Q3 25', orders: 15187, returns: 3037, prevented: 31,  returnRate: 20.0, tag: 'Kept starts' },
        { label: 'Q4 25', orders: 19818, returns: 3150, prevented: 393, returnRate: 15.9 },
        { label: 'Jan 26', orders: 6087, returns: 664, prevented: 207,  returnRate: 10.9 },
      ],
    },
    reasonsData: [
      { name: 'Wrong Shade/Color', pct: 36, count: 194, color: '#073159' },
      { name: 'Allergic Reaction', pct: 21, count: 113, color: '#2E9CDB' },
      { name: 'Not as Described',  pct: 19, count: 103, color: '#3B4A6B' },
      { name: 'Product Expired',   pct: 11, count: 59,  color: '#5BB8E8' },
      { name: 'Arrived Damaged',   pct: 8,  count: 43,  color: '#A0AEC0' },
      { name: 'Other',             pct: 5,  count: 27,  color: '#CBD5E0' },
    ],
    products: [
      {
        id: 'vsf-401', name: 'Velvet Silk Foundation', cat: 'Face',
        sku: 'VSF-401', price: 48, sold: 1247, returned: 327, returnRate: 26.2,
        topReason: 'Wrong Shade', reasonPct: 78, returnCost: 6538, risk: 'critical',
      },
      {
        id: 'hlp-220', name: 'Hydra-Luxe Lip Palette', cat: 'Lips',
        sku: 'HLP-220', price: 36, sold: 883, returned: 191, returnRate: 21.6,
        topReason: 'Not as Described', reasonPct: 65, returnCost: 3827, risk: 'high',
      },
      {
        id: 'rgs-115', name: 'Retinol Glow Serum', cat: 'Skincare',
        sku: 'RGS-115', price: 72, sold: 643, returned: 159, returnRate: 24.7,
        topReason: 'Allergic Reaction', reasonPct: 82, returnCost: 4773, risk: 'critical',
      },
      {
        id: 'mep-330', name: 'Mineral Eye Palette 12-pan', cat: 'Eyes',
        sku: 'MEP-330', price: 54, sold: 774, returned: 143, returnRate: 18.5,
        topReason: 'Wrong Shade', reasonPct: 58, returnCost: 4291, risk: 'high',
      },
    ],
    aiInsights: {
      'vsf-401': {
        product: 'Velvet Silk Foundation — VSF-401',
        summary: '78% of returns cite "Wrong Shade." The online shade finder relies on self-reported skin tone categories (fair/medium/dark) which are too broad. Customers in the medium range are split across 8 shades with no visual comparison tool.',
        actions: [
          { priority: 'high', text: 'Implement an AI shade-matching quiz using uploaded selfies with lighting normalization.', impact: 'Est. -20% return rate → saves ~$3,200/quarter' },
          { priority: 'high', text: 'Add side-by-side swatch comparisons for adjacent shades on PDP.', impact: 'Est. -10% return rate → saves ~$1,600/quarter' },
          { priority: 'medium', text: 'Offer a sample kit ($5 for 3 shades, credited toward purchase).', impact: 'Est. -8% return rate → saves ~$1,280/quarter' },
        ]
      },
      'hlp-220': {
        product: 'Hydra-Luxe Lip Palette — HLP-220',
        summary: '65% cite "Not as Described." Product photography over-saturates the colors — real swatches are 2-3 shades muted compared to product images.',
        actions: [
          { priority: 'high', text: 'Reshoot product with calibrated color-accurate photography. Include arm swatches on 4 skin tones.', impact: 'Est. -14% return rate → saves ~$1,370/quarter' },
          { priority: 'medium', text: 'Add user-submitted swatch photos to PDP with a review incentive.', impact: 'Est. -7% return rate → saves ~$685/quarter' },
        ]
      },
      'rgs-115': {
        product: 'Retinol Glow Serum — RGS-115',
        summary: '82% cite "Allergic Reaction." The 1.5% retinol concentration is high for first-time users. No sensitivity warning or patch test recommendation exists on the product page.',
        actions: [
          { priority: 'high', text: 'Add a "Skin Sensitivity Check" at checkout — flag first-time retinol buyers and recommend the 0.5% starter version.', impact: 'Est. -18% return rate → saves ~$2,200/quarter' },
          { priority: 'high', text: 'Add prominent "Patch test recommended" warning with instructions on PDP.', impact: 'Est. -8% return rate → saves ~$980/quarter' },
          { priority: 'medium', text: 'Bundle with a soothing recovery balm sample to reduce irritation-driven returns.', impact: 'Est. -5% return rate → saves ~$610/quarter' },
        ]
      },
      'mep-330': {
        product: 'Mineral Eye Palette 12-pan — MEP-330',
        summary: '58% cite "Wrong Shade." The palette name ("Sunset Boulevard") implies warm tones, but 5 of 12 pans are cool-toned neutrals. Customers expecting a fully warm palette are disappointed.',
        actions: [
          { priority: 'high', text: 'Rename palette to "Sunset & Smoke" to set accurate warm/cool expectations. Update marketing copy.', impact: 'Est. -10% return rate → saves ~$1,110/quarter' },
          { priority: 'medium', text: 'Add a tone-map graphic on PDP showing which pans are warm vs cool.', impact: 'Est. -6% return rate → saves ~$665/quarter' },
        ]
      },
    },
    returnRateTrend: [
      { label: 'Aug', rate: 14.1 },
      { label: 'Sep', rate: 13.6 },
      { label: 'Oct', rate: 12.8 },
      { label: 'Nov', rate: 11.9 },
      { label: 'Dec', rate: 11.2 },
      { label: 'Jan', rate: 10.4 },
    ],
    channelData: [
      { channel: 'Online Store', returns: 312, pct: 58, rate: 13.1 },
      { channel: 'Marketplace', returns: 143, pct: 27, rate: 10.8 },
      { channel: 'Mobile App', returns: 54, pct: 10, rate: 9.2 },
      { channel: 'In-Store', returns: 30, pct: 5, rate: 4.7 },
    ],
    interventions: [
      { type: 'Shade Match Quiz', triggered: 587, prevented: 211, rate: 35.9 },
      { type: 'Sensitivity Check', triggered: 312, prevented: 134, rate: 42.9 },
      { type: 'Swatch Comparison', triggered: 198, prevented: 63, rate: 31.8 },
      { type: 'Review Highlights', triggered: 143, prevented: 37, rate: 25.9 },
    ],
  },

  'techgear-pro': {
    name: 'TechGear Pro',
    initials: 'TG',
    avgReturnCost: 57.7,
    avgOrderValue: 146.5,
    industry: 'Consumer Electronics',
    datasets: {
      '7D': [
        { label: 'Jan 25', orders: 83,  returns: 11, prevented: 5, returnRate: 13.3 },
        { label: 'Jan 26', orders: 74,  returns: 7,  prevented: 3, returnRate: 9.5 },
        { label: 'Jan 27', orders: 91,  returns: 11, prevented: 4, returnRate: 12.1 },
        { label: 'Jan 28', orders: 103, returns: 12, prevented: 6, returnRate: 11.7 },
        { label: 'Jan 29', orders: 86,  returns: 8,  prevented: 3, returnRate: 9.3 },
        { label: 'Jan 30', orders: 113, returns: 14, prevented: 7, returnRate: 12.4 },
        { label: 'Jan 31', orders: 97,  returns: 11, prevented: 5, returnRate: 11.3 },
      ],
      '30D': [
        { label: 'Jan 1',  orders: 109, returns: 17, prevented: 3, returnRate: 15.6 },
        { label: 'Jan 3',  orders: 107, returns: 17, prevented: 5, returnRate: 15.9 },
        { label: 'Jan 5',  orders: 96,  returns: 13, prevented: 3, returnRate: 13.5 },
        { label: 'Jan 7',  orders: 94,  returns: 14, prevented: 5, returnRate: 14.9 },
        { label: 'Jan 9',  orders: 106, returns: 14, prevented: 4, returnRate: 13.2 },
        { label: 'Jan 11', orders: 103, returns: 14, prevented: 6, returnRate: 13.6 },
        { label: 'Jan 13', orders: 91,  returns: 11, prevented: 3, returnRate: 12.1 },
        { label: 'Jan 15', orders: 107, returns: 14, prevented: 6, returnRate: 13.1 },
        { label: 'Jan 17', orders: 96,  returns: 11, prevented: 4, returnRate: 11.5 },
        { label: 'Jan 19', orders: 93,  returns: 11, prevented: 5, returnRate: 11.8 },
        { label: 'Jan 21', orders: 99,  returns: 10, prevented: 4, returnRate: 10.1 },
        { label: 'Jan 23', orders: 97,  returns: 11, prevented: 5, returnRate: 11.3 },
        { label: 'Jan 25', orders: 83,  returns: 11, prevented: 5, returnRate: 13.3 },
        { label: 'Jan 27', orders: 91,  returns: 11, prevented: 4, returnRate: 12.1 },
        { label: 'Jan 31', orders: 97,  returns: 11, prevented: 5, returnRate: 11.3 },
      ],
      '3M': [
        { label: 'Nov W1', orders: 617, returns: 109, prevented: 13, returnRate: 17.7 },
        { label: 'Nov W2', orders: 683, returns: 121, prevented: 19, returnRate: 17.7 },
        { label: 'Nov W3', orders: 743, returns: 124, prevented: 17, returnRate: 16.7 },
        { label: 'Nov W4', orders: 714, returns: 123, prevented: 21, returnRate: 17.2 },
        { label: 'Dec W1', orders: 787, returns: 128, prevented: 31, returnRate: 16.3 },
        { label: 'Dec W2', orders: 803, returns: 118, prevented: 29, returnRate: 14.7 },
        { label: 'Dec W3', orders: 773, returns: 119, prevented: 36, returnRate: 15.4 },
        { label: 'Dec W4', orders: 717, returns: 104, prevented: 28, returnRate: 14.5 },
        { label: 'Jan W1', orders: 687, returns: 91, prevented: 37, returnRate: 13.2 },
        { label: 'Jan W2', orders: 647, returns: 76, prevented: 33, returnRate: 11.7 },
        { label: 'Jan W3', orders: 633, returns: 74, prevented: 35, returnRate: 11.7 },
        { label: 'Jan W4', orders: 593, returns: 63, prevented: 29, returnRate: 10.6 },
      ],
      '1Y': [
        { label: 'Feb',  orders: 1413, returns: 243, prevented: 0,  returnRate: 17.2 },
        { label: 'Mar',  orders: 1487, returns: 264, prevented: 0,  returnRate: 17.8 },
        { label: 'Apr',  orders: 1557, returns: 299, prevented: 0,  returnRate: 19.2 },
        { label: 'May',  orders: 1593, returns: 314, prevented: 0,  returnRate: 19.7 },
        { label: 'Jun',  orders: 1713, returns: 363, prevented: 0,  returnRate: 21.2 },
        { label: 'Jul',  orders: 1787, returns: 389, prevented: 0,  returnRate: 21.8 },
        { label: 'Aug',  orders: 2113, returns: 491, prevented: 0,  returnRate: 23.2 },
        { label: 'Sep',  orders: 2287, returns: 498, prevented: 16, returnRate: 21.8, tag: 'Kept starts' },
        { label: 'Oct',  orders: 2517, returns: 509, prevented: 51, returnRate: 20.2 },
        { label: 'Nov',  orders: 2793, returns: 497, prevented: 79, returnRate: 17.8 },
        { label: 'Dec',  orders: 3087, returns: 490, prevented: 124, returnRate: 15.9 },
        { label: 'Jan',  orders: 2613, returns: 319, prevented: 147, returnRate: 12.2 },
      ],
      'ALL': [
        { label: 'Q1 24', orders: 3217,  returns: 519, prevented: 0,   returnRate: 16.1 },
        { label: 'Q2 24', orders: 3793,  returns: 639, prevented: 0,   returnRate: 16.8 },
        { label: 'Q3 24', orders: 4187,  returns: 746, prevented: 0,   returnRate: 17.8 },
        { label: 'Q4 24', orders: 4613,  returns: 884, prevented: 0,   returnRate: 19.2 },
        { label: 'Q1 25', orders: 4437,  returns: 879, prevented: 0,   returnRate: 19.8 },
        { label: 'Q2 25', orders: 5093,  returns: 1064, prevented: 0,  returnRate: 20.9 },
        { label: 'Q3 25', orders: 6213,  returns: 1373, prevented: 16, returnRate: 22.1, tag: 'Kept starts' },
        { label: 'Q4 25', orders: 8397,  returns: 1496, prevented: 254, returnRate: 17.8 },
        { label: 'Jan 26', orders: 2613, returns: 319, prevented: 147, returnRate: 12.2 },
      ],
    },
    reasonsData: [
      { name: 'Compatibility Issues', pct: 33, count: 161, color: '#073159' },
      { name: 'Not as Described',     pct: 24, count: 117, color: '#2E9CDB' },
      { name: 'Defective/DOA',        pct: 19, count: 93,  color: '#3B4A6B' },
      { name: 'Missing Features',     pct: 11, count: 54,  color: '#5BB8E8' },
      { name: 'Changed Mind',         pct: 8,  count: 39,  color: '#A0AEC0' },
      { name: 'Other',                pct: 5,  count: 24,  color: '#CBD5E0' },
    ],
    products: [
      {
        id: 'uwc-500', name: 'UltraCharge Wireless Dock', cat: 'Accessories',
        sku: 'UWC-500', price: 79, sold: 514, returned: 152, returnRate: 29.6,
        topReason: 'Compatibility', reasonPct: 76, returnCost: 6089, risk: 'critical',
      },
      {
        id: 'nca-700', name: 'NoiseCancel AirPods Max', cat: 'Audio',
        sku: 'NCA-700', price: 249, sold: 337, returned: 86, returnRate: 25.5,
        topReason: 'Not as Described', reasonPct: 68, returnCost: 8617, risk: 'critical',
      },
      {
        id: 'smw-200', name: 'SmartFit Watch Pro', cat: 'Wearables',
        sku: 'SMW-200', price: 199, sold: 483, returned: 113, returnRate: 23.4,
        topReason: 'Compatibility', reasonPct: 71, returnCost: 9041, risk: 'high',
      },
      {
        id: 'pbt-100', name: 'PowerBank Titan 20K', cat: 'Power',
        sku: 'PBT-100', price: 59, sold: 673, returned: 126, returnRate: 18.7,
        topReason: 'Defective', reasonPct: 62, returnCost: 3782, risk: 'high',
      },
    ],
    aiInsights: {
      'uwc-500': {
        product: 'UltraCharge Wireless Dock — UWC-500',
        summary: '76% cite "Compatibility Issues." The dock supports Qi2 only, but the product page doesn\'t clearly state that older Qi1 devices won\'t fast-charge. 44% of returns are from Samsung Galaxy S21/S22 users.',
        actions: [
          { priority: 'high', text: 'Add a device compatibility checker on PDP — input phone model, get instant confirmation.', impact: 'Est. -18% return rate → saves ~$2,810/quarter' },
          { priority: 'high', text: 'Add checkout warning when detected device (via account data) isn\'t Qi2 compatible.', impact: 'Est. -10% return rate → saves ~$1,560/quarter' },
          { priority: 'medium', text: 'Update product title to include "Qi2 Only" designation.', impact: 'Est. -5% return rate → saves ~$780/quarter' },
        ]
      },
      'nca-700': {
        product: 'NoiseCancel AirPods Max — NCA-700',
        summary: '68% cite "Not as Described." Noise cancellation marketing claims "99% ambient noise reduction" but real-world testing shows 78-85%. Customers also report discomfort after 90+ minutes.',
        actions: [
          { priority: 'high', text: 'Revise marketing claims to "up to 85% noise reduction" with transparent testing methodology.', impact: 'Est. -12% return rate → saves ~$2,640/quarter' },
          { priority: 'medium', text: 'Add comfort duration guidance: "Designed for sessions up to 2 hours" with ear cushion upgrade upsell.', impact: 'Est. -8% return rate → saves ~$1,760/quarter' },
        ]
      },
      'smw-200': {
        product: 'SmartFit Watch Pro — SMW-200',
        summary: '71% cite "Compatibility Issues." The watch app requires iOS 16+ or Android 13+, cutting off ~22% of potential users with older OS versions.',
        actions: [
          { priority: 'high', text: 'Add OS version check at checkout with clear minimum requirements callout.', impact: 'Est. -14% return rate → saves ~$3,080/quarter' },
          { priority: 'medium', text: 'Develop a legacy companion app with limited features for older OS versions.', impact: 'Est. -6% return rate → saves ~$1,320/quarter' },
        ]
      },
      'pbt-100': {
        product: 'PowerBank Titan 20K — PBT-100',
        summary: '62% cite "Defective." QA analysis shows batch PBT-100-B3 has a 34% failure rate on USB-C port — a connector soldering issue from supplier changeover in October.',
        actions: [
          { priority: 'high', text: 'Recall batch B3 units and switch back to original supplier. Offer affected customers free replacement.', impact: 'Est. -25% return rate → saves ~$2,420/quarter' },
          { priority: 'medium', text: 'Implement incoming QA spot-check on USB-C port stress test for all new batches.', impact: 'Est. -5% return rate → saves ~$485/quarter' },
        ]
      },
    },
    returnRateTrend: [
      { label: 'Aug', rate: 15.3 },
      { label: 'Sep', rate: 14.7 },
      { label: 'Oct', rate: 13.9 },
      { label: 'Nov', rate: 12.4 },
      { label: 'Dec', rate: 11.1 },
      { label: 'Jan', rate: 10.2 },
    ],
    channelData: [
      { channel: 'Online Store', returns: 247, pct: 51, rate: 14.9 },
      { channel: 'Marketplace', returns: 168, pct: 34, rate: 11.3 },
      { channel: 'Mobile App', returns: 49, pct: 10, rate: 8.6 },
      { channel: 'In-Store', returns: 24, pct: 5, rate: 5.1 },
    ],
    interventions: [
      { type: 'Spec Comparison Tool', triggered: 324, prevented: 126, rate: 38.9 },
      { type: 'Compatibility Check', triggered: 267, prevented: 107, rate: 40.1 },
      { type: 'Video Demo Prompt', triggered: 189, prevented: 55, rate: 29.1 },
      { type: 'Review Highlights', triggered: 112, prevented: 31, rate: 27.7 },
    ],
  },

  'homenest': {
    name: 'HomeNest Living',
    initials: 'HN',
    avgReturnCost: 262.2,
    avgOrderValue: 684.0,
    industry: 'Home & Furniture',
    datasets: {
      '7D': [
        { label: 'Jan 25', orders: 47, returns: 7,  prevented: 3, returnRate: 14.9 },
        { label: 'Jan 26', orders: 43, returns: 8,  prevented: 2, returnRate: 18.6 },
        { label: 'Jan 27', orders: 53, returns: 9,  prevented: 3, returnRate: 17.0 },
        { label: 'Jan 28', orders: 62, returns: 11, prevented: 5, returnRate: 17.7 },
        { label: 'Jan 29', orders: 49, returns: 7,  prevented: 3, returnRate: 14.3 },
        { label: 'Jan 30', orders: 67, returns: 12, prevented: 6, returnRate: 17.9 },
        { label: 'Jan 31', orders: 56, returns: 8,  prevented: 3, returnRate: 14.3 },
      ],
      '30D': [
        { label: 'Jan 1',  orders: 71, returns: 16, prevented: 4, returnRate: 22.5 },
        { label: 'Jan 3',  orders: 59, returns: 12, prevented: 2, returnRate: 20.3 },
        { label: 'Jan 5',  orders: 61, returns: 13, prevented: 4, returnRate: 21.3 },
        { label: 'Jan 7',  orders: 53, returns: 10, prevented: 2, returnRate: 18.9 },
        { label: 'Jan 9',  orders: 66, returns: 13, prevented: 5, returnRate: 19.7 },
        { label: 'Jan 11', orders: 54, returns: 10, prevented: 3, returnRate: 18.5 },
        { label: 'Jan 13', orders: 51, returns: 10, prevented: 3, returnRate: 19.6 },
        { label: 'Jan 15', orders: 63, returns: 12, prevented: 5, returnRate: 19.0 },
        { label: 'Jan 17', orders: 57, returns: 11, prevented: 4, returnRate: 19.3 },
        { label: 'Jan 19', orders: 48, returns: 8,  prevented: 2, returnRate: 16.7 },
        { label: 'Jan 21', orders: 57, returns: 9,  prevented: 3, returnRate: 15.8 },
        { label: 'Jan 23', orders: 54, returns: 10, prevented: 4, returnRate: 18.5 },
        { label: 'Jan 25', orders: 47, returns: 7,  prevented: 3, returnRate: 14.9 },
        { label: 'Jan 27', orders: 53, returns: 9,  prevented: 3, returnRate: 17.0 },
        { label: 'Jan 31', orders: 56, returns: 8,  prevented: 3, returnRate: 14.3 },
      ],
      '3M': [
        { label: 'Nov W1', orders: 383, returns: 101, prevented: 11, returnRate: 26.4 },
        { label: 'Nov W2', orders: 417, returns: 102, prevented: 13, returnRate: 24.5 },
        { label: 'Nov W3', orders: 453, returns: 111, prevented: 18, returnRate: 24.5 },
        { label: 'Nov W4', orders: 407, returns: 99,  prevented: 12, returnRate: 24.3 },
        { label: 'Dec W1', orders: 487, returns: 113, prevented: 24, returnRate: 23.2 },
        { label: 'Dec W2', orders: 497, returns: 102, prevented: 23, returnRate: 20.5 },
        { label: 'Dec W3', orders: 473, returns: 101, prevented: 29, returnRate: 21.4 },
        { label: 'Dec W4', orders: 437, returns: 89,  prevented: 22, returnRate: 20.4 },
        { label: 'Jan W1', orders: 407, returns: 79,  prevented: 31, returnRate: 19.4 },
        { label: 'Jan W2', orders: 377, returns: 66,  prevented: 24, returnRate: 17.5 },
        { label: 'Jan W3', orders: 363, returns: 63,  prevented: 27, returnRate: 17.4 },
        { label: 'Jan W4', orders: 337, returns: 52,  prevented: 22, returnRate: 15.4 },
      ],
      '1Y': [
        { label: 'Feb',  orders: 827,  returns: 201, prevented: 0,  returnRate: 24.3 },
        { label: 'Mar',  orders: 873,  returns: 216, prevented: 0,  returnRate: 24.7 },
        { label: 'Apr',  orders: 923,  returns: 243, prevented: 0,  returnRate: 26.3 },
        { label: 'May',  orders: 957,  returns: 255, prevented: 0,  returnRate: 26.6 },
        { label: 'Jun',  orders: 1027, returns: 291, prevented: 0,  returnRate: 28.3 },
        { label: 'Jul',  orders: 1093, returns: 314, prevented: 0,  returnRate: 28.7 },
        { label: 'Aug',  orders: 1307, returns: 409, prevented: 0,  returnRate: 31.3 },
        { label: 'Sep',  orders: 1387, returns: 413, prevented: 11, returnRate: 29.8, tag: 'Kept starts' },
        { label: 'Oct',  orders: 1563, returns: 424, prevented: 46, returnRate: 27.1 },
        { label: 'Nov',  orders: 1657, returns: 391, prevented: 61, returnRate: 23.6 },
        { label: 'Dec',  orders: 1897, returns: 402, prevented: 103, returnRate: 21.2 },
        { label: 'Jan',  orders: 1513, returns: 269, prevented: 104, returnRate: 17.8 },
      ],
      'ALL': [
        { label: 'Q1 24', orders: 1813, returns: 383, prevented: 0,   returnRate: 21.1 },
        { label: 'Q2 24', orders: 2187, returns: 478, prevented: 0,   returnRate: 21.9 },
        { label: 'Q3 24', orders: 2617, returns: 607, prevented: 0,   returnRate: 23.2 },
        { label: 'Q4 24', orders: 2887, returns: 717, prevented: 0,   returnRate: 24.8 },
        { label: 'Q1 25', orders: 2627, returns: 714, prevented: 0,   returnRate: 27.2 },
        { label: 'Q2 25', orders: 2993, returns: 833, prevented: 0,   returnRate: 27.8 },
        { label: 'Q3 25', orders: 3787, returns: 1131, prevented: 11, returnRate: 29.9, tag: 'Kept starts' },
        { label: 'Q4 25', orders: 5117, returns: 1217, prevented: 210, returnRate: 23.8 },
        { label: 'Jan 26', orders: 1513, returns: 269, prevented: 104, returnRate: 17.8 },
      ],
    },
    reasonsData: [
      { name: 'Wrong Size/Dimensions', pct: 31, count: 147, color: '#073159' },
      { name: 'Color Mismatch',        pct: 23, count: 109, color: '#2E9CDB' },
      { name: 'Assembly Issues',        pct: 19, count: 90,  color: '#3B4A6B' },
      { name: 'Quality Below Expected', pct: 13, count: 62,  color: '#5BB8E8' },
      { name: 'Arrived Damaged',        pct: 9,  count: 43,  color: '#A0AEC0' },
      { name: 'Other',                  pct: 5,  count: 24,  color: '#CBD5E0' },
    ],
    products: [
      {
        id: 'mss-800', name: 'Modern Sectional Sofa', cat: 'Living Room',
        sku: 'MSS-800', price: 1299, sold: 117, returned: 44, returnRate: 37.6,
        topReason: 'Wrong Size', reasonPct: 74, returnCost: 22877, risk: 'critical',
      },
      {
        id: 'wdr-450', name: 'Woven Dining Rug 8x10', cat: 'Rugs',
        sku: 'WDR-450', price: 389, sold: 213, returned: 67, returnRate: 31.5,
        topReason: 'Color Mismatch', reasonPct: 82, returnCost: 10453, risk: 'critical',
      },
      {
        id: 'fbf-220', name: 'Floating Bed Frame Queen', cat: 'Bedroom',
        sku: 'FBF-220', price: 599, sold: 177, returned: 45, returnRate: 25.4,
        topReason: 'Assembly Issues', reasonPct: 68, returnCost: 10782, risk: 'high',
      },
      {
        id: 'mbc-150', name: 'Marble Console Table', cat: 'Entryway',
        sku: 'MBC-150', price: 449, sold: 163, returned: 39, returnRate: 23.9,
        topReason: 'Quality Below Expected', reasonPct: 71, returnCost: 7021, risk: 'high',
      },
    ],
    aiInsights: {
      'mss-800': {
        product: 'Modern Sectional Sofa — MSS-800',
        summary: '74% cite "Wrong Size." The sofa\'s listed dimensions (112" x 86") don\'t include armrests and seat depth. Customers in apartments under 800 sq ft consistently return — the sofa overwhelms smaller rooms.',
        actions: [
          { priority: 'high', text: 'Add an AR room visualizer using phone camera — let customers see the sofa in their actual space before buying.', impact: 'Est. -20% return rate → saves ~$11,960/quarter' },
          { priority: 'high', text: 'Update dimensions to include "total footprint with clearance" measurements and add a room size recommendation.', impact: 'Est. -10% return rate → saves ~$5,980/quarter' },
          { priority: 'medium', text: 'Add a "Will it fit?" quiz: input room dimensions, doorway width, and elevator size for delivery feasibility.', impact: 'Est. -8% return rate → saves ~$4,784/quarter' },
        ]
      },
      'wdr-450': {
        product: 'Woven Dining Rug 8x10 — WDR-450',
        summary: '82% cite "Color Mismatch." The rug\'s natural fiber color shifts significantly between dye lots. Studio photos show a warm ivory, but recent batches skew more gray-beige.',
        actions: [
          { priority: 'high', text: 'Add batch-specific color photos to PDP and note "Natural color variation — your rug may differ slightly from photo."', impact: 'Est. -16% return rate → saves ~$4,056/quarter' },
          { priority: 'medium', text: 'Offer free fabric swatches mailed in 2-3 days before purchase.', impact: 'Est. -10% return rate → saves ~$2,535/quarter' },
        ]
      },
      'fbf-220': {
        product: 'Floating Bed Frame Queen — FBF-220',
        summary: '68% cite "Assembly Issues." The instruction manual has 47 steps with small diagrams. Average assembly time is 3.5 hours vs. the advertised 45 minutes. 23% of returns mention stripped screws.',
        actions: [
          { priority: 'high', text: 'Create a step-by-step video assembly guide (QR code in box + PDP). Redesign manual with full-page diagrams.', impact: 'Est. -14% return rate → saves ~$3,948/quarter' },
          { priority: 'high', text: 'Upgrade to pre-drilled pilot holes and include a hex key with torque limiter to prevent stripping.', impact: 'Est. -8% return rate → saves ~$2,256/quarter' },
        ]
      },
      'mbc-150': {
        product: 'Marble Console Table — MBC-150',
        summary: '71% cite "Quality Below Expected." The "marble" top is actually marble-look engineered stone. Product copy says "genuine marble finish" which implies real marble.',
        actions: [
          { priority: 'high', text: 'Update product name to "Marble-Look Console Table" and description to clearly state "engineered stone with marble finish."', impact: 'Est. -15% return rate → saves ~$2,498/quarter' },
          { priority: 'medium', text: 'Add close-up material texture photos and a "Materials & Care" section on PDP.', impact: 'Est. -8% return rate → saves ~$1,332/quarter' },
        ]
      },
    },
    returnRateTrend: [
      { label: 'Aug', rate: 19.4 },
      { label: 'Sep', rate: 18.7 },
      { label: 'Oct', rate: 17.1 },
      { label: 'Nov', rate: 15.6 },
      { label: 'Dec', rate: 14.2 },
      { label: 'Jan', rate: 12.8 },
    ],
    channelData: [
      { channel: 'Online Store', returns: 263, pct: 56, rate: 18.4 },
      { channel: 'Marketplace', returns: 108, pct: 23, rate: 14.1 },
      { channel: 'Mobile App', returns: 71, pct: 15, rate: 11.7 },
      { channel: 'In-Store', returns: 33, pct: 6, rate: 7.3 },
    ],
    interventions: [
      { type: 'Dimension Visualizer', triggered: 287, prevented: 103, rate: 35.9 },
      { type: 'Room Fit Calculator', triggered: 213, prevented: 81, rate: 38.0 },
      { type: 'Material Swatch Modal', triggered: 164, prevented: 48, rate: 29.3 },
      { type: 'Assembly Preview', triggered: 97, prevented: 29, rate: 29.9 },
    ],
  },

  'peakfit': {
    name: 'PeakFit Athletics',
    initials: 'PF',
    avgReturnCost: 37.2,
    avgOrderValue: 84.3,
    industry: 'Sportswear & Activewear',
    datasets: {
      '7D': [
        { label: 'Jan 25', orders: 163, returns: 19, prevented: 8,  returnRate: 11.7 },
        { label: 'Jan 26', orders: 151, returns: 18, prevented: 8,  returnRate: 11.9 },
        { label: 'Jan 27', orders: 177, returns: 22, prevented: 9,  returnRate: 12.4 },
        { label: 'Jan 28', orders: 197, returns: 23, prevented: 12, returnRate: 11.7 },
        { label: 'Jan 29', orders: 169, returns: 18, prevented: 8,  returnRate: 10.7 },
        { label: 'Jan 30', orders: 207, returns: 26, prevented: 13, returnRate: 12.6 },
        { label: 'Jan 31', orders: 184, returns: 20, prevented: 9,  returnRate: 10.9 },
      ],
      '30D': [
        { label: 'Jan 1',  orders: 203, returns: 33, prevented: 8,  returnRate: 16.3 },
        { label: 'Jan 3',  orders: 186, returns: 28, prevented: 6,  returnRate: 15.1 },
        { label: 'Jan 5',  orders: 181, returns: 28, prevented: 8,  returnRate: 15.5 },
        { label: 'Jan 7',  orders: 166, returns: 24, prevented: 6,  returnRate: 14.5 },
        { label: 'Jan 9',  orders: 193, returns: 28, prevented: 9,  returnRate: 14.5 },
        { label: 'Jan 11', orders: 177, returns: 24, prevented: 7,  returnRate: 13.6 },
        { label: 'Jan 13', orders: 173, returns: 24, prevented: 8,  returnRate: 13.9 },
        { label: 'Jan 15', orders: 183, returns: 23, prevented: 8,  returnRate: 12.6 },
        { label: 'Jan 17', orders: 177, returns: 23, prevented: 9,  returnRate: 13.0 },
        { label: 'Jan 19', orders: 159, returns: 19, prevented: 7,  returnRate: 11.9 },
        { label: 'Jan 21', orders: 181, returns: 22, prevented: 10, returnRate: 12.2 },
        { label: 'Jan 23', orders: 167, returns: 19, prevented: 7,  returnRate: 11.4 },
        { label: 'Jan 25', orders: 163, returns: 19, prevented: 8,  returnRate: 11.7 },
        { label: 'Jan 27', orders: 177, returns: 22, prevented: 9,  returnRate: 12.4 },
        { label: 'Jan 31', orders: 184, returns: 20, prevented: 9,  returnRate: 10.9 },
      ],
      '3M': [
        { label: 'Nov W1', orders: 1193, returns: 237, prevented: 22, returnRate: 19.9 },
        { label: 'Nov W2', orders: 1307, returns: 257, prevented: 33, returnRate: 19.7 },
        { label: 'Nov W3', orders: 1373, returns: 258, prevented: 31, returnRate: 18.8 },
        { label: 'Nov W4', orders: 1287, returns: 247, prevented: 33, returnRate: 19.2 },
        { label: 'Dec W1', orders: 1413, returns: 251, prevented: 39, returnRate: 17.8 },
        { label: 'Dec W2', orders: 1467, returns: 253, prevented: 51, returnRate: 17.2 },
        { label: 'Dec W3', orders: 1393, returns: 234, prevented: 47, returnRate: 16.8 },
        { label: 'Dec W4', orders: 1327, returns: 228, prevented: 49, returnRate: 17.2 },
        { label: 'Jan W1', orders: 1253, returns: 184, prevented: 49, returnRate: 14.7 },
        { label: 'Jan W2', orders: 1207, returns: 171, prevented: 53, returnRate: 14.2 },
        { label: 'Jan W3', orders: 1147, returns: 147, prevented: 46, returnRate: 12.8 },
        { label: 'Jan W4', orders: 1107, returns: 136, prevented: 51, returnRate: 12.3 },
      ],
      '1Y': [
        { label: 'Feb',  orders: 2813, returns: 540, prevented: 0,   returnRate: 19.2 },
        { label: 'Mar',  orders: 2987, returns: 591, prevented: 0,   returnRate: 19.8 },
        { label: 'Apr',  orders: 3163, returns: 669, prevented: 0,   returnRate: 21.2 },
        { label: 'May',  orders: 3287, returns: 717, prevented: 0,   returnRate: 21.8 },
        { label: 'Jun',  orders: 3513, returns: 814, prevented: 0,   returnRate: 23.2 },
        { label: 'Jul',  orders: 3687, returns: 878, prevented: 0,   returnRate: 23.8 },
        { label: 'Aug',  orders: 4213, returns: 1059, prevented: 0,  returnRate: 25.1 },
        { label: 'Sep',  orders: 4487, returns: 1073, prevented: 19, returnRate: 23.9, tag: 'Kept starts' },
        { label: 'Oct',  orders: 4813, returns: 1063, prevented: 71, returnRate: 22.1 },
        { label: 'Nov',  orders: 5287, returns: 997, prevented: 117, returnRate: 18.9 },
        { label: 'Dec',  orders: 5613, returns: 961, prevented: 191, returnRate: 17.1 },
        { label: 'Jan',  orders: 4793, returns: 617, prevented: 194, returnRate: 12.9 },
      ],
      'ALL': [
        { label: 'Q1 24', orders: 5987,  returns: 949,  prevented: 0,   returnRate: 15.9 },
        { label: 'Q2 24', orders: 7213,  returns: 1231, prevented: 0,   returnRate: 17.1 },
        { label: 'Q3 24', orders: 8187,  returns: 1465, prevented: 0,   returnRate: 17.9 },
        { label: 'Q4 24', orders: 9013,  returns: 1721, prevented: 0,   returnRate: 19.1 },
        { label: 'Q1 25', orders: 8763,  returns: 1761, prevented: 0,   returnRate: 20.1 },
        { label: 'Q2 25', orders: 9937,  returns: 2075, prevented: 0,   returnRate: 20.9 },
        { label: 'Q3 25', orders: 12387, returns: 2973, prevented: 19,  returnRate: 24.0, tag: 'Kept starts' },
        { label: 'Q4 25', orders: 15713, returns: 3021, prevented: 379, returnRate: 19.2 },
        { label: 'Jan 26', orders: 4793, returns: 617,  prevented: 194, returnRate: 12.9 },
      ],
    },
    reasonsData: [
      { name: 'Size / Fit Issues',  pct: 37, count: 193, color: '#073159' },
      { name: 'Fabric Feel/Comfort', pct: 23, count: 120, color: '#2E9CDB' },
      { name: 'Not as Described',    pct: 17, count: 89,  color: '#3B4A6B' },
      { name: 'Color Different',     pct: 11, count: 57,  color: '#5BB8E8' },
      { name: 'Quality Issues',      pct: 7,  count: 37,  color: '#A0AEC0' },
      { name: 'Other',               pct: 5,  count: 26,  color: '#CBD5E0' },
    ],
    products: [
      {
        id: 'crl-600', name: 'Compression Run Legging', cat: 'Bottoms',
        sku: 'CRL-600', price: 78, sold: 913, returned: 298, returnRate: 32.6,
        topReason: 'Wrong Size', reasonPct: 79, returnCost: 11623, risk: 'critical',
      },
      {
        id: 'fzh-310', name: 'FlexZone Hoodie', cat: 'Tops',
        sku: 'FZH-310', price: 65, sold: 787, returned: 199, returnRate: 25.3,
        topReason: 'Fabric Feel', reasonPct: 66, returnCost: 5967, risk: 'critical',
      },
      {
        id: 'trs-440', name: 'Trail Runner Speed', cat: 'Footwear',
        sku: 'TRS-440', price: 142, sold: 537, returned: 127, returnRate: 23.6,
        topReason: 'Wrong Size', reasonPct: 73, returnCost: 7239, risk: 'high',
      },
      {
        id: 'msb-250', name: 'Marathon Sports Bra', cat: 'Tops',
        sku: 'MSB-250', price: 52, sold: 647, returned: 134, returnRate: 20.7,
        topReason: 'Wrong Size', reasonPct: 81, returnCost: 3354, risk: 'high',
      },
    ],
    aiInsights: {
      'crl-600': {
        product: 'Compression Run Legging — CRL-600',
        summary: '79% cite "Wrong Size." The compression fit runs 1 full size smaller than standard athletic sizing. Size chart uses generic S/M/L without noting the compression factor.',
        actions: [
          { priority: 'high', text: 'Add "Compression fit — size up one size for standard fit" guidance prominently on PDP and at checkout.', impact: 'Est. -20% return rate → saves ~$5,928/quarter' },
          { priority: 'high', text: 'Deploy Kept widget with body measurement quiz for personalized size recommendation.', impact: 'Est. -12% return rate → saves ~$3,557/quarter' },
          { priority: 'medium', text: 'Add customer fit photos by size in reviews section.', impact: 'Est. -5% return rate → saves ~$1,482/quarter' },
        ]
      },
      'fzh-310': {
        product: 'FlexZone Hoodie — FZH-310',
        summary: '66% cite "Fabric Feel." The hoodie uses a new recycled polyester blend that feels rougher than the previous cotton-poly mix. Product page still references "ultra-soft fleece interior."',
        actions: [
          { priority: 'high', text: 'Update product description to accurately describe the recycled poly fabric. Remove "ultra-soft" claim.', impact: 'Est. -14% return rate → saves ~$2,048/quarter' },
          { priority: 'medium', text: 'Add a fabric composition and texture description section with close-up texture photos.', impact: 'Est. -8% return rate → saves ~$1,170/quarter' },
          { priority: 'medium', text: 'Consider reverting to cotton-poly blend or softening treatment for recycled polyester.', impact: 'Est. -10% return rate → saves ~$1,463/quarter' },
        ]
      },
      'trs-440': {
        product: 'Trail Runner Speed — TRS-440',
        summary: '73% cite "Wrong Size." The shoe runs wide in the midfoot but narrow in the toe box, creating a confusing fit. International size conversion (EU/UK) is also off by half a size.',
        actions: [
          { priority: 'high', text: 'Add width profile info (narrow toe / standard midfoot) and recommend trying half size up for narrow feet.', impact: 'Est. -15% return rate → saves ~$2,779/quarter' },
          { priority: 'high', text: 'Fix international size conversion chart — EU sizes 40-45 are off by 0.5.', impact: 'Est. -8% return rate → saves ~$1,482/quarter' },
        ]
      },
      'msb-250': {
        product: 'Marathon Sports Bra — MSB-250',
        summary: '81% cite "Wrong Size." The bra uses band/cup sizing (32A-38DD) but most customers only know their S/M/L t-shirt size. No size conversion guide exists.',
        actions: [
          { priority: 'high', text: 'Add S/M/L to band/cup conversion chart and a "Find your size" quiz on PDP.', impact: 'Est. -18% return rate → saves ~$1,544/quarter' },
          { priority: 'medium', text: 'Add a checkout prompt: "Not sure about sports bra sizing? Take our 30-second fit quiz."', impact: 'Est. -10% return rate → saves ~$856/quarter' },
        ]
      },
    },
    returnRateTrend: [
      { label: 'Aug', rate: 21.2 },
      { label: 'Sep', rate: 20.1 },
      { label: 'Oct', rate: 18.6 },
      { label: 'Nov', rate: 16.9 },
      { label: 'Dec', rate: 15.4 },
      { label: 'Jan', rate: 13.7 },
    ],
    channelData: [
      { channel: 'Online Store', returns: 289, pct: 55, rate: 17.8 },
      { channel: 'Marketplace', returns: 126, pct: 24, rate: 13.2 },
      { channel: 'Mobile App', returns: 79, pct: 15, rate: 10.9 },
      { channel: 'In-Store', returns: 28, pct: 6, rate: 6.4 },
    ],
    interventions: [
      { type: 'Size Guide Prompt', triggered: 378, prevented: 140, rate: 37.0 },
      { type: 'Fit Confirmation', triggered: 256, prevented: 97, rate: 37.9 },
      { type: 'Activity Match Quiz', triggered: 174, prevented: 58, rate: 33.3 },
      { type: 'Review Highlights', triggered: 102, prevented: 28, rate: 27.5 },
    ],
  },
};
